artifacts:
  linreg:
    path: models/lr_model
    type: model
    meta:
      framework: sklearn
stages:
  preprocess:
    cmd: python src/data/preproc_data.py
    deps:
    - data/raw/ts_data.csv
    - src/data/preproc_data.py
    params:
    - preprocess.num_lagged_features
    outs:
    - data/preprocessed/ts_data_monthly.csv
    - data/preprocessed/ts_data_monthly.csv.mlem:
        cache: false # track with Git; not dvc
  visualize:
    cmd: python src/viz/visualize.py
    deps:
    - data/raw/ts_data.csv
    - data/preprocessed/ts_data_monthly.csv
    - src/viz/visualize.py
    params:
    - visualize.differencing_param
    - visualize.num_lags_to_plot
    outs:
    - reports/figures/daily_timeseries.png:
        cache: false # track using Git; not dvc
    - reports/figures/monthly_timeseries.png:
        cache: false # track using Git; not dvc
    - reports/figures/daily_acf.png:
        cache: false # track using Git; not dvc
    - reports/figures/monthly_acf.png:
        cache: false # track using Git; not dvc
  train_model:
    cmd: python src/models/train_model.py
    deps:
    - data/preprocessed/ts_data_monthly.csv
    - src/models/train_model.py
    params:
    - train_model.num_splits
    - train_model.forecast_size
    - train_model.model_fit_intercept
    - train_model.model_force_positive_coeffs
    outs:
    - reports/figures/validation_forecasts.png:
        cache: false # track using Git; not dvc
    - models/lr_model
    - models/metrics.json:
        cache: false # track using Git; not dvc
metrics:
- models/metrics.json
plots:
- reports/figures/daily_timeseries.png
- reports/figures/monthly_timeseries.png
- reports/figures/daily_acf.png
- reports/figures/monthly_acf.png
