name: run-workflow

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: iterative/setup-cml@v1

      - uses: iterative/setup-dvc@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: cml
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |

          # install requirements from file
          pip install -r requirements.txt

          # pull data & model with dvc
          dvc pull

          # reproduce pipeline
          dvc repro

          # use dvc metrics diff to compare metrics to master
          git fetch --prune --unshallow
          dvc metrics diff --show-md prod >> reports/report.md

          # add figures to report
          echo '![](./reports/figures/validation_forecasts.png)' >> reports/report.md
          cml comment create --pr --publish reports/report.md
