name: Build and Deploy to AWS

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push Docker image
      id: build-image
      run: |
        docker build -t ${{ secrets.ECR_REGISTRY }}/lr_model:latest ./build
        docker push ${{ secrets.ECR_REGISTRY }}/lr_model:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Install AWS CLI
      run: |
        sudo apt-get install -y awscli

    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster devops_cluster --service serve --force-new-deployment
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-2
